# Fundamentals Exercises

Key elements of a program
- Identation: Separa bloques visualmente generando una jerarquia que es visual y lógico, clave para comprender el flow del programa 
- Statement: linea de codigo que hace una función específica, cada statement es un paso simple en el programa, es el workforce del codigo
- Variables: containers digitales para guardar data, en diversos formatos, listas, numeros, strings
- Comments: Explicar logicas, dar contexto en forma de texto, no afectan el código

# Python Basics

In [27]:
#Import libraries

import numpy as np
import pandas as pd

In [ ]:
#testing notebook

print("Hello, world")

Hello, world

## Basic operations 

Why use python for math?
- Speed and efficiency
- Accuracy 
- Automation
- Flexibility

In [2]:
#Define variables 
x = 8 
y = 2
z = 'string'

In [ ]:
# Addition 
result = x + y
print('addition example', result)

# Subtraction
result = x - y
print('subtraction example', result)

# Multiplication
result = x * y
print('multiplication example', result)

# Division
result = x / y
print('division example', result)

# Modulo
result = x % y
print('modulo example', result)

# Exponent
result = x ** y
print('exponent example', result)

# Floor division
result = x // y
print('floor division example', result)

#notar que el modulo es el resto de la division entera
# notar que floor division es la division entera, por ejemplo 5//2 = 2
#notar que result cambia de valor por cada operacion, se mantiene el valor de la ultima operacion

addition example 10
subtraction example 6
multiplication example 16
division example 4.0
modulo example 0
exponent example 64
floor division example 4

## Statements

In [ ]:
#statement and identation example 

age = 25 
if age >= 18:
    print("You are eligible to vote.")
else:
    print("You are not yet eligible to vote.")

You are eligible to vote.

In [ ]:
# general loop example

for i in range(5):
    print(i)
#notar que range comienza en 0 y llega hasta n-1 cuando range(n)

0
1
2
3
4

Addressing potential concerns and best practices

While loops and conditional statements are powerful tools, their overuse or improper implementation can lead to complex and difficult-to-maintain code. It's important to follow best practices to ensure code clarity and efficiency. 

Keep loops concise: Avoid nesting loops too deeply, as this can make the code harder to understand and debug. Break down complex loops into smaller, more manageable chunks. Think of it like organizing a closet: it's much easier to find what you're looking for when things are neatly arranged and categorized.

Use meaningful conditions: Ensure that the conditions used in conditional statements are clear and easy to understand. Avoid overly complex conditions that can obfuscate the code's logic. Clear and concise conditions make it easier for others (and your future self!) to understand the intent of your code.

Consider alternative constructs: In some cases, alternative constructs like list comprehensions or lambda functions can provide more concise and efficient ways to achieve the same result as loops and conditional statements. These constructs can sometimes provide a more elegant and readable solution, especially for simple operations.

Avoid infinite loops: Be cautious to ensure that the loop condition eventually becomes False. Failing to do so can cause an infinite loop, which might crash your program or require manual termination.

In [25]:
import random

secret_number = 8

guess = 0
counter = 0

while (secret_number != guess):
    counter = counter + 1
    guess = random.randint(1, 10)
    print("Guessing:",guess)

print("Counter:",counter)
print("I guessed the right number! It was",secret_number)

Guessing: 2
Guessing: 5
Guessing: 3
Guessing: 3
Guessing: 7
Guessing: 6
Guessing: 4
Guessing: 2
Guessing: 9
Guessing: 7
Guessing: 6
Guessing: 5
Guessing: 4
Guessing: 7
Guessing: 1
Guessing: 4
Guessing: 5
Guessing: 2
Guessing: 2
Guessing: 5
Guessing: 8
Counter: 21
I guessed the right number! It was 8

In [ ]:
# working with a csv 

import csv

with open('data.csv', 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)
        
# reader es un objeto que permite leer el archivo csv

In [8]:
#Decision statement, if, elif, else example

truck_capacity = 247 #tons

if truck_capacity > 0:
    print("Truck Capacity is well defined")
else:
    print("Truck Capacity is not well defined")
     
    
if truck_capacity > 200:
    print("Truck is class A") 
elif truck_capacity > 100:
    print("Truck is class B")
else:
    print("Truck is class C")

Truck Capacity is well defined
Truck is class A

In [5]:
''' EXAMPLE from course
Children (under 12): $8
Adults (12-64): $12
Seniors (65 and over): $10
'''

def ticket_price(age):
    if age < 12:
        return 8
    elif age < 65:
        return 12
    else:
        return 10

In [7]:
age = 25
price = ticket_price(age)
print("Ticket price for age", age, "is", price, 'dollars')

Ticket price for age 25 is 12 dollars

In [ ]:
#   example of "if" for avoid crash of a program 

# Realistic mining example

def calculate_throughput_tph(processed_tons: float, operating_hours: float) -> float | None:
    """
    Calculate plant throughput in tons per hour.

    Returns None when operating_hours is zero or negative,
    because throughput cannot be safely calculated.
    """
    if operating_hours <= 0:
        print("Warning: operating_hours must be greater than 0. Throughput was not calculated.")
        return None

    throughput_tph = processed_tons / operating_hours
    return throughput_tph

In [3]:
# Using calculate_throughput_tph function
processed_tons = 12_500
operating_hours = 72

throughput = calculate_throughput_tph(processed_tons, operating_hours)

print(throughput)

173.61111111111111

Optimizing decision structures: Looking beyond basic constructs

While if, elif, and else provide a solid foundation for decision-making in Python, there are situations where alternative approaches can lead to more efficient and readable code.

Dictionary mapping: When dealing with multiple choices based on a single key value, dictionaries can offer a cleaner solution. For example, instead of a long chain of elif clauses to determine shipping costs based on country codes, a dictionary can map country codes to shipping rates, making the code more concise, readable, and easier to update.

Utilizing Python libraries: Python offers powerful libraries like NumPy and pandas that provide optimized functions for performing conditional operations on arrays and dataframes, often significantly faster than manual implementations. Leveraging these libraries can not only improve code efficiency but also reduce development time and effort.

In [ ]:
# simbolo de diferente es !=, igual es ==, mayor es >, menor es <, mayor o igual es >=, menor o igual es <=, not es !, and es &, or es | 

x = 5
y = 10

print(x != y)

True

## Ambiente python-dev --> generado por JCA con conda env 

Lo clave es que usa Pytho 3.11.15, el del mac como tal era el 3.9.6

¿Quiero analizar datos?              → pandas, numpy
¿Quiero visualizar?                  → matplotlib, seaborn
¿Quiero modelar?                     → scikit-learn
¿Quiero usar notebooks?              → jupyter, ipykernel
¿Quiero comprobar que funciona?      → pytest
¿Quiero código limpio?               → ruff, black
¿Quiero revisar type hints?          → mypy

Comandos bash para la instalación desde terminal 

conda activate python-dev

conda install pandas numpy matplotlib seaborn scikit-learn jupyter ipykernel pytest ruff black mypy

## For and While loops

distinction between for and while loops is that for loops iterate over a known sequence, while while loops iterate until a condition becomes false. Understanding the best practices for using loops, such as choosing the appropriate loop type for the task, optimizing loop performance, and avoiding common pitfalls like infinite loops, is crucial for maximizing their effectiveness.

In [8]:
start = 2
end = 13
step = 2

# for i loop
for i in range(start, end , step):
    # Code block to be executed repeatedly
    print(i)

2
4
6
8
10
12

In [9]:
import random
roll = 0
while roll != 6:
    roll = random.randint(1, 6) 
    print("You rolled a", roll)

You rolled a 4
You rolled a 3
You rolled a 1
You rolled a 3
You rolled a 3
You rolled a 4
You rolled a 1
You rolled a 1
You rolled a 4
You rolled a 5
You rolled a 1
You rolled a 1
You rolled a 2
You rolled a 6

In [11]:
numbers = [1, 2, 3, 4, 5]
index = 0 # el indice comienza en cero y se usa para recorrer la lista, cero es el primer elemento
print('largo de lista', len(numbers))
print('        ') 

while index < len(numbers):
    if numbers[index] % 2 == 0: #indica si el numero es par
        print('el index es ',index)
        print('El numero es ',numbers[index])
    index += 1 #aumenta el indice en uno

largo de lista 5

el index es  1
El numero es  2
el index es  3
El numero es  4

In [14]:
# nested loops 

for i in range(1, 11):
    for j in range(1, 11):
        print(i, "*", j, "=", i * j, end="\t") # Print the equation
    print() # Move to the next line after each row
# end="\t") es para que se imprima en una sola linea
#this is a multiplication table

1 * 1 = 1	1 * 2 = 2	1 * 3 = 3	1 * 4 = 4	1 * 5 = 5	1 * 6 = 6	1 * 7 = 7	1 * 8 = 8	1 * 9 = 9	1 * 10 = 10
2 * 1 = 2	2 * 2 = 4	2 * 3 = 6	2 * 4 = 8	2 * 5 = 10	2 * 6 = 12	2 * 7 = 14	2 * 8 = 16	2 * 9 = 18	2 * 10 = 20
3 * 1 = 3	3 * 2 = 6	3 * 3 = 9	3 * 4 = 12	3 * 5 = 15	3 * 6 = 18	3 * 7 = 21	3 * 8 = 24	3 * 9 = 27	3 * 10 = 30
4 * 1 = 4	4 * 2 = 8	4 * 3 = 12	4 * 4 = 16	4 * 5 = 20	4 * 6 = 24	4 * 7 = 28	4 * 8 = 32	4 * 9 = 36	4 * 10 = 40
5 * 1 = 5	5 * 2 = 10	5 * 3 = 15	5 * 4 = 20	5 * 5 = 25	5 * 6 = 30	5 * 7 = 35	5 * 8 = 40	5 * 9 = 45	5 * 10 = 50
6 * 1 = 6	6 * 2 = 12	6 * 3 = 18	6 * 4 = 24	6 * 5 = 30	6 * 6 = 36	6 * 7 = 42	6 * 8 = 48	6 * 9 = 54	6 * 10 = 60
7 * 1 = 7	7 * 2 = 14	7 * 3 = 21	7 * 4 = 28	7 * 5 = 35	7 * 6 = 42	7 * 7 = 49	7 * 8 = 56	7 * 9 = 63	7 * 10 = 70
8 * 1 = 8	8 * 2 = 16	8 * 3 = 24	8 * 4 = 32	8 * 5 = 40	8 * 6 = 48	8 * 7 = 56	8 * 8 = 64	8 * 9 = 72	8 * 10 = 80
9 * 1 = 9	9 * 2 = 18	9 * 3 = 27	9 * 4 = 36	9 * 5 = 45	9 * 6 = 54	9 * 7 = 63	9 * 8 = 72	9 * 9 = 81	9 * 10 = 90
10 * 1 = 10	10 * 2 = 20	10 * 3 = 30	10 * 4 = 40	10 * 5 = 50	10 * 6 = 60	10 * 7 = 70	10 * 8 = 80	10 * 9 = 90	10 * 10 = 100

In [15]:
print("hello")

print("world")

hello
world

In [16]:
print("hello", end="\t")

print("world", end="\t")

hello	world

# Functional Code Challenge: Leveraging `for` Loops

## Objective

Use a `for` loop to print all numbers from `0` to `max_value` that are evenly divisible by **both 3 and 4**.

A number is evenly divisible by another number when the remainder of the division is `0`.

For example:

- `16` is divisible by `4`, but not by `3`, so it should **not** be printed.
- `18` is divisible by `3`, but not by `4`, so it should **not** be printed.
- `19` is divisible by neither `3` nor `4`, so it should **not** be printed.
- `24` is divisible by both `3` and `4`, so it **should** be printed.

## Starter Variable

```python
max_value = 50

In [19]:
max_value = 50 

for i in range(0, max_value + 1):
    if i % 3 == 0 and i % 4 == 0: # si es divisible por 3 y 4
        print(i)

0
12
24
36
48

In [20]:
#challenge number even or odd 
numbers = [3, 9, 1, 10, 5, 2, 8]

for number in numbers:
    if number % 2 == 0:
        print(number, "is even")
    else:
        print(number, "is odd")

3 is odd
9 is odd
1 is odd
10 is even
5 is odd
2 is even
8 is even

In [25]:
#loop to count down from 10 to 0
# add time to the print of the loop
import time 

for i in range(10, -1, -1):
    if i == 5:
        print("Halfway reached!")
    print(i)
    time.sleep(1)

10
9
8
7
6
Halfway reached!
5
4
3
2
1
0

Tracing code execution 

interpreter: transforma el programa de alto nivel python a lengauje de maquina

call stack: estructura de data que las llamadas a funciones activas en el programa

debugging: muestra donde ocurre el error, puedes seguir el camino de ejecucion del programa, entender la logica del programa es clave para eso

Tracing, es clave para debugging, print() es la herramienta básica para tracing, im

1. identation error: misplaced indent, Solution: Always pay meticulous attention to your indentation. Ensure that statements within loops, conditionals, functions, and classes are properly indented. Most code editors provide visual cues to help you maintain consistent indentation.


2. Variable scope: region of your code where the variable is accesible. Solution: Be mindful of where you define your variables. If you need a variable to be accessible throughout your code, define it in the global scope. However, excessive use of global variables can lead to code that's harder to maintain, so use them judiciously.

3. Immutable values:  strings are immutable, meaning their contents cannot be changed after they're created. 

4. Variable reassignment: Solution: Choose distinct names for your variables to avoid this issue. Some other programming languages have stricter rules and might not allow this, so this happens more commonly in Python than other languages.

5. Overlooking exceptions: When a possibility or an exception exists (such as trying to open a missing file, or referencing a variable that doesn't exist), you will use try-except blocks to gracefully handle exceptions, like this code example:  

6. advance: circular import, Memory management, Testing and debugging: Thoroughly test your code and use debugging tools to identify and fix errors. Testing and debugging are like regular check-ups for your code.

In [ ]:
# exercise Variables and loops STEP 1

# Create a list and add sample Celsius temperatures to it 
celsius_temperatures = [] # Start with an empty list (do not modify)

# Add the Celsius temperatures to the list
#### Insert code here
celsius_temperatures.extend([0, 10, 25, 35, 100])

# Create an empty list to store Fahrenheit temperatures
#### Insert code here
fahrenheit_temperatures = []

# Print both lists (do not modify)
print("Celsius Temperatures:", celsius_temperatures)
print("Fahrenheit Temperatures:", fahrenheit_temperatures)

Celsius Temperatures: [0, 10, 25, 35, 100]
Fahrenheit Temperatures: []

In [29]:
# exercise Variables and loops STEP 2

# Lists from Step 1 (do not modify)
celsius_temperatures = [0, 10, 25, 32, 100]
fahrenheit_temperatures = [] 

# Convert each Celsius temperature to Fahrenheit
for celsius in celsius_temperatures:  # Start the loop (do not modify this line)
  fahrenheit =  celsius*(9/5)+32  ##### Insert code here

  fahrenheit_temperatures.append(fahrenheit)  # Append to the list (do not modify this line)

# Print the results (including the output from Step 1 - do not modify)
print("Celsius Temperatures:", celsius_temperatures)
print("Fahrenheit Temperatures:", fahrenheit_temperatures)

Celsius Temperatures: [0, 10, 25, 32, 100]
Fahrenheit Temperatures: [32.0, 50.0, 77.0, 89.6, 212.0]

In [30]:
#List Comprehensions
# [expression for item in list if condition]

# Example 1: Convert Celsius temperatures to Fahrenheit
celsius_temperatures = [0, 10, 25, 32, 100]
fahrenheit_temperatures = [celsius*(9/5)+32 for celsius in celsius_temperatures]

print("Celsius Temperatures:", celsius_temperatures)
print("Fahrenheit Temperatures:", fahrenheit_temperatures)

Celsius Temperatures: [0, 10, 25, 32, 100]
Fahrenheit Temperatures: [32.0, 50.0, 77.0, 89.6, 212.0]

TABLA RESUMEN DE OPERACIONES CON LISTAS
Command
What it does
len(list)
Tells you how many things are in the list.
list.append(x)
Adds x to the end of the list.
list.insert(i, x)
Adds x at position i in the list.
list.remove(x)
Removes the first x from the list.
list.sort()
Arranges the list in order.
list.reverse()
Reverses the order of the items in the list.
list.count(x)
Counts how many times x appears in the list.
x in list
Checks if x is in the list.
list.index(x)
Tells you the position of the first x in the list

In [ ]:
customer_feedback = [
    "  Great SERVICE!  ",
    " Product arrived LATE ",
    "  I LOVE the quality   ",
    "Too EXPENSIVE"
]

clean_feedback = [text.strip().lower() for text in customer_feedback]

# .strip elimina los espacios en blanco al principio y al final
# .lower pasa todo a minuscula

print(clean_feedback)

['great service!', 'product arrived late', 'i love the quality', 'too expensive']

## Functions

- Reusable blocks of code to be reusable 
- Miniprograms 
- Robust, Mantainable, organization of the code.
- abstraction, focus in higher level logic, not in implementations details.

- ​There are three different kinds of functions in Python. ​The first is built-in functions. ​Python comes with a number of predefined functions, like print, len, and input. ​They provide essential functionalities, saving you the trouble of writing code from scratch. ​The second type are user-defined functions, which are functions that you create to perform ​specific tasks in your program. ​The third type of functions are lambda functions, which are anonymous, one-line functions that ​are often used for simple operations or as arguments to other functions. ​For example, if you have a list of employees with their salaries, you can use a lambda ​function to sort the list based on salary in descending order. 

- Functions typically perform actions, so starting with a verb like calculate, get, filter, validate, or process sets the right tone.
- If a function is intended for internal use within a module and shouldn't be accessed directly from outside, prefix its name with an underscore (_). For instance, _calculate_internal_metrics. For functions that return a boolean value (True/False), strongly consider using prefixes like is_, has_, or can_ to instantly signal their nature.
- A central principle in software design, the Single Responsibility Principle (SRP), plays a pivotal role in determining when to decompose a function. The SRP states that a class or module (and by extension, a function) should have only one reason to change. In simpler terms, a function should do one thing and do it well.
-

In [ ]:
def is_valid_email(email):
    # ... (Validation logic)
    return True  # Or False based on validation

def has_sufficient_balance(account):
    # ... (Balance check logic)
    return True  # Or False based on balance

def can_access_resource(user, resource):
    # ... (Permission check logic)
    return True  # Or False based on permissions

""" 
DOCSTRING OF A FUNCTION 
Arguments

A detailed list of all input parameters, including:

Clear and descriptive names that match the function's internal variables.

The expected data types of each argument (int, float, str, list, dict). These are called type hints.

Brief explanations of what each argument represents and how it's used.

An indication of whether each argument is optional or mandatory. If optional, provide default values.

Return value

A clear description of the data type and meaning of the value returned by the function. If the function doesn't return anything (None), state it explicitly.
"""

In [ ]:
def calculate_monthly_payment(principal: float, interest_rate: float, loan_term_years: int) -> float:
    """
    Calculates the monthly payment for a fixed-rate loan.

    Args:
        principal: The total amount borrowed (float).
        interest_rate: The annual interest rate (as a decimal, float).
        loan_term_years: The loan term in years (int).

    Returns:
        The monthly payment amount (float).

    Raises:
        ValueError: If any of the inputs are negative or zero.

    Example:
        >>> calculate_monthly_payment(100000, 0.05, 30)
        530.33 
    """
    if principal <= 0 or interest_rate <= 0 or loan_term_years <= 0:
        raise ValueError("All input values must be positive.")

    monthly_interest_rate = interest_rate / 12
    number_of_payments = loan_term_years * 12
    
    # Calculation logic for monthly payment (omitted for brevity)

    return monthly_payment

In [ ]:
# function example generic 

def function_name(arguments): #arguments are the parameters that will be passed to the function
    # body of the function
    #body is the code that will be executed when the function is called
    # value is the value that will be returned when the function is called
    return value

In [32]:
# area de rectangulio 

def area_rectangle(width, height):
    """
    Calculate the area of a rectangle.
    Formula:
        area = width * height
    The function attempts to convert both inputs to floats. If either input
    cannot be converted to a numeric value, or if either value is less than
    than or equal to zero, the function returns None.
    Parameters
    ----------
    width : int | float | str
        Rectangle width. Must be convertible to a positive float.
    height : int | float | str
        Rectangle height. Must be convertible to a positive float.
    Returns
    -------
    float | None
        The rectangle area as a float if inputs are valid; otherwise, None.
    """
    try:
        width = float(width)
        height = float(height)
    except (ValueError, TypeError):
        return None

    if width <= 0 or height <= 0:
        return None

    area = width * height
    return area

In [33]:
# Example usage:
length = 5
width = 3
rectangle_area = area_rectangle(length, width) # Function call, providing inputs
print(f"The area of the rectangle is: {rectangle_area}") # Using the output

The area of the rectangle is: 15.0

In [8]:
def calculate_diameter_circle(radius: int | float) -> float:
    """
    Calculate the diameter of a circle given its radius.

    Parameters
    ----------
    radius : int | float
        Radius of the circle. It must be a positive number.

    Returns
    -------
    float
        Diameter of the circle. Returns -1.0 if the radius is negative.
    """
    if radius < 0:
        return -1.0

    diameter = 2 * radius
    return float(diameter)

## Art of abstraction

- DRY (Don't Repeat Yourself) principle emerged in the 1990s, popularized by Andy Hunt and Dave Thomas in their seminal book, "The Pragmatic Programmer."
single source of truth, ensuring consistency and simplifying updates. 

- Now, what happens when we look at existing code and realize it's not as DRY or well-structured as it could be? That's where the idea of refactoring comes in.

- Refactoring is the process of restructuring existing computer code—changing the factoring—without changing its external behavior. Essentially, it's about cleaning up your code after it's written to improve its design, readability, and maintainability. Think of it as going back to those building blocks we talked about (functions) and rearranging or refining them to make the entire structure more solid and easier to work with in the long run.  

As a rule of thumb, consider these factors when deciding whether to create a function:

Frequency of use: If a code snippet is used multiple times, encapsulating it in a function promotes reusability and simplifies maintenance.

Complexity: If a task involves multiple steps or intricate logic, a function can improve readability and make the code more modular.

Likelihood of change: If a piece of code is likely to evolve over time, a function provides a centralized point of modification, reducing the risk of inconsistencies.

Modern Python:
- Dexcorators : @caché spetial functions that modifyes other functions
- Generators: produce sequence of values on demand
- F-strings: Dynamic output f"Hello, {name}! Today is {date.today()}."
- Type Hints:  specify the expected data types for function arguments and return values, def calculate_area(length: float, width: float) -> float: ...

In [ ]:
help(len)

In [35]:
# ============================================================
# 30 BUILT-IN FUNCTIONS IMPORTANTES EN PYTHON
# Perfil: Data Science, análisis de datos, automatización y minería
# ============================================================

# 1. print()
# Muestra información en pantalla. Muy útil para inspeccionar resultados.
print("1. print(): Hola, estoy aprendiendo Python profesionalmente")


# 2. type()
# Muestra el tipo de dato de una variable.
value = 10.5
print("2. type():", type(value))


# 3. len()
# Cuenta elementos en una lista, caracteres en un string, filas en una colección, etc.
truck_ids = ["T001", "T002", "T003", "T004"]
print("3. len(): Número de camiones:", len(truck_ids))


# 4. int()
# Convierte un valor a número entero.
value_text = "25"
print("4. int():", int(value_text))


# 5. float()
# Convierte un valor a número decimal.
cu_grade_text = "0.85"
print("5. float(): Ley de cobre:", float(cu_grade_text))


# 6. str()
# Convierte un valor a texto.
truck_id = 125
print("6. str(): Truck_" + str(truck_id))


# 7. bool()
# Convierte un valor a True o False.
has_valid_sensor = 1
print("7. bool(): Sensor válido:", bool(has_valid_sensor))


# 8. input()
# Permite ingresar información manualmente.
# En notebooks puede pedirte escribir un valor.
# user_name = input("Escribe tu nombre: ")
# print("8. input(): Hola", user_name)


# 9. sum()
# Suma los valores de una colección numérica.
daily_tonnage = [1200, 1350, 1280, 1400]
print("9. sum(): Tonelaje total:", sum(daily_tonnage))


# 10. max()
# Entrega el valor máximo.
cu_grades = [0.25, 0.55, 0.12, 1.20, 0.85]
print("10. max(): Mayor ley de cobre:", max(cu_grades))


# 11. min()
# Entrega el valor mínimo.
print("11. min(): Menor ley de cobre:", min(cu_grades))


# 12. round()
# Redondea un número decimal.
average_grade = 0.846372
print("12. round(): Ley promedio redondeada:", round(average_grade, 2))


# 13. abs()
# Entrega el valor absoluto. Útil para calcular errores sin signo.
real_value = 0.90
predicted_value = 0.82
error = predicted_value - real_value
print("13. abs(): Error absoluto:", abs(error))


# 14. sorted()
# Ordena una colección sin modificar la original.
grades = [0.8, 0.2, 1.1, 0.5]
print("14. sorted(): Leyes ordenadas:", sorted(grades))


# 15. list()
# Convierte un objeto iterable en lista.
material_codes = ("OX", "SUL", "MIX")
print("15. list():", list(material_codes))


# 16. tuple()
# Convierte una colección en tupla, que es inmutable.
coordinates = [350000, 6300000, 1250]
print("16. tuple(): Coordenadas como tupla:", tuple(coordinates))


# 17. dict()
# Crea un diccionario clave-valor.
truck_record = dict(truck_id="T001", tonnes=320, cu_grade=0.75)
print("17. dict():", truck_record)


# 18. set()
# Elimina duplicados y deja valores únicos.
materials = ["waste", "ore", "ore", "waste", "low_grade"]
print("18. set(): Materiales únicos:", set(materials))


# 19. range()
# Genera una secuencia de números. Muy usado en loops.
print("19. range():")
for i in range(5):
    print("Iteración:", i)


# 20. enumerate()
# Entrega índice y valor al recorrer una colección.
samples = ["S001", "S002", "S003"]
print("20. enumerate():")
for index, sample in enumerate(samples):
    print(f"Índice {index}: muestra {sample}")


# 21. zip()
# Une varias listas elemento a elemento.
truck_ids = ["T001", "T002", "T003"]
tonnes = [320, 280, 350]

print("21. zip():")
for truck, tonne in zip(truck_ids, tonnes):
    print(f"Camión {truck} transportó {tonne} toneladas")


# 22. any()
# Retorna True si al menos una condición es verdadera.
sensor_status = [False, False, True]
print("22. any(): ¿Existe algún sensor activo?", any(sensor_status))


# 23. all()
# Retorna True solo si todas las condiciones son verdaderas.
quality_checks = [True, True, True]
print("23. all(): ¿Todos los chequeos pasaron?", all(quality_checks))


# 24. isinstance()
# Verifica si una variable pertenece a cierto tipo de dato.
value = 0.95
print("24. isinstance(): ¿value es float?", isinstance(value, float))


# 25. map()
# Aplica una función a cada elemento de una colección.
grades_percent = [0.1, 0.2, 0.35, 0.8]

def convert_to_ppm(grade_percent):
    """Convierte porcentaje a ppm."""
    return grade_percent * 10_000

grades_ppm = list(map(convert_to_ppm, grades_percent))
print("25. map(): Leyes en ppm:", grades_ppm)


# 26. filter()
# Filtra elementos según una condición.
grades = [0.05, 0.12, 0.20, 0.08, 0.50]

def is_ore(grade):
    """Retorna True si la ley está sobre el cutoff."""
    cutoff = 0.10
    return grade >= cutoff

ore_grades = list(filter(is_ore, grades))
print("26. filter(): Leyes sobre cutoff:", ore_grades)


# 27. sorted() con key
# Ordena estructuras más complejas usando una clave.
trucks = [
    {"truck_id": "T001", "tonnes": 320},
    {"truck_id": "T002", "tonnes": 280},
    {"truck_id": "T003", "tonnes": 350},
]

trucks_sorted = sorted(trucks, key=lambda truck: truck["tonnes"], reverse=True)
print("27. sorted() con key:", trucks_sorted)


# 28. open()
# Abre archivos para leer o escribir.
# Este ejemplo crea un archivo de texto simple.
with open("example_report.txt", "w", encoding="utf-8") as file:
    file.write("Reporte operacional generado con Python.\n")

print("28. open(): Archivo example_report.txt creado correctamente")


# 29. help()
# Muestra documentación de una función, clase o método.
# Útil para aprender sin salir de Python.
# Descomenta la línea siguiente si quieres ver la ayuda de len().
# help(len)


# 30. dir()
# Muestra los métodos y atributos disponibles para un objeto.
text = "Copper Grade"
print("30. dir(): Algunos métodos disponibles para strings:")
print(dir(text)[:10])  # Mostramos solo los primeros 10 para no saturar la salida

1. print(): Hola, estoy aprendiendo Python profesionalmente
2. type(): <class 'float'>
3. len(): Número de camiones: 4
4. int(): 25
5. float(): Ley de cobre: 0.85
6. str(): Truck_125
7. bool(): Sensor válido: True
9. sum(): Tonelaje total: 5230
10. max(): Mayor ley de cobre: 1.2
11. min(): Menor ley de cobre: 0.12
12. round(): Ley promedio redondeada: 0.85
13. abs(): Error absoluto: 0.08000000000000007
14. sorted(): Leyes ordenadas: [0.2, 0.5, 0.8, 1.1]
15. list(): ['OX', 'SUL', 'MIX']
16. tuple(): Coordenadas como tupla: (350000, 6300000, 1250)
17. dict(): {'truck_id': 'T001', 'tonnes': 320, 'cu_grade': 0.75}
18. set(): Materiales únicos: {'waste', 'low_grade', 'ore'}
19. range():
Iteración: 0
Iteración: 1
Iteración: 2
Iteración: 3
Iteración: 4
20. enumerate():
Índice 0: muestra S001
Índice 1: muestra S002
Índice 2: muestra S003
21. zip():
Camión T001 transportó 320 toneladas
Camión T002 transportó 280 toneladas
Camión T003 transportó 350 toneladas
22. any(): ¿Existe algún sensor activo? True
23. all(): ¿Todos los chequeos pasaron? True
24. isinstance(): ¿value es float? True
25. map(): Leyes en ppm: [1000.0, 2000.0, 3500.0, 8000.0]
26. filter(): Leyes sobre cutoff: [0.12, 0.2, 0.5]
27. sorted() con key: [{'truck_id': 'T003', 'tonnes': 350}, {'truck_id': 'T001', 'tonnes': 320}, {'truck_id': 'T002', 'tonnes': 280}]
28. open(): Archivo example_report.txt creado correctamente
30. dir(): Algunos métodos disponibles para strings:
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__']

Math Exercise 1: Analyzing Antarctic Temperatures  

Instructions:

Begin with the antarctic_temperatures list, which contains the daily temperature recordings.

Apply the max() function to the antarctic_temperatures list to obtain the highest temperature recorded.

Apply the min() function on the antarctic_temperatures list to determine the lowest temperature recorded.

Print the highest and lowest temperatures.

Calculate the average temperature by summing all temperatures in the antarctic_temperatures list using the sum() function and dividing by the number of temperatures, which you can determine using the len() function. Round the calculated average temperature to one decimal place using the round() function.

Print the rounded average temperature.

Calculate the absolute value of the coldest temperature using the abs() function.

Print the absolute value of the coldest temperature.

In [39]:
antarctic_temperatures = [-25.5, -28.0, -26.3, -23.8, -27.1, -24.9, -29.2]

# Find the highest and lowest temperatures
highest_temp = max(antarctic_temperatures) ### Insert code here
lowest_temp = min(antarctic_temperatures) ### Insert code here

print("Highest temperature:", highest_temp, "°C")
print("Lowest temperature:", lowest_temp, "°C")

# Calculate the average temperature
average_temp = sum(antarctic_temperatures)/len(antarctic_temperatures) ### Insert code here
average_temp = round(average_temp)
print("Average temperature:", average_temp, "°C")

# Find the absolute value of the coldest temperature
coldest_temp_abs = abs(lowest_temp) ### Insert code here
print("The coldest temperature was", coldest_temp_abs, "°C below freezing.")

Highest temperature: -23.8 °C
Lowest temperature: -29.2 °C
Average temperature: -26 °C
The coldest temperature was 29.2 °C below freezing.

In [37]:
#data types

int_value = 15
float_value = 4.1
text_value = "33"

type_of_float_value = type(float_value) # STEP 2: YOUR CODE HERE

# Convert text_value to an integer
text_value_as_int = int(text_value)# STEP 3: YOUR CODE HERE

# Convert int_value to text
int_value_as_text = str(int_value)# STEP 4: YOUR CODE HERE

# DO NOT CHANGE LINES BELOW
# Print the type of float_value
print("float_value type:", type_of_float_value)

# Adding text_value_as_int to int_value
print("Integer addition: Adding text_value_as_int (33) to int_value (15):", text_value_as_int + int_value)

# Adding (concatenating) text values
print("Text addition: Adding text_value (33) to int_value_as_text (15):", text_value + int_value_as_text)

float_value type: <class 'float'>
Integer addition: Adding text_value_as_int (33) to int_value (15): 48
Text addition: Adding text_value (33) to int_value_as_text (15): 3315

## Modules

- Cada modulo se encarga de una parte específica del código, funciones específicas 
- es una forma de mantener el código organizado y estructurado

Variable Scope
- Local: solo accesibles en ciertas partes del codigo
- Global: son accesible desde cualquier parte del codigo 
- Modifying a global variable in one function can have unintended consequences in other parts of your code that rely on it. This can lead to subtle bugs that are difficult to track down.

The LEGB rule: Python's search strategy for variables

When you use a variable in your code, Python embarks on a systematic search to find its value. The search order is described by the LEGB rule:

Local (L): Python first checks if the variable exists within the current function or code block.

Enclosing (E): If not found locally, it looks in enclosing functions (if you're using nested functions, like Russian dolls).

Global (G): Next, it searches the global scope, i.e., variables defined at the top level of your module.

Built-in (B): Finally, it checks Python's built-in namespace for pre-defined functions and objects like print, list, etc.

This hierarchical search ensures that Python always finds the most relevant value for a variable, preventing conflicts between variables with the same name at different levels.

In [40]:
# Global variable
COMPANY_NAME = "Global Tech Solutions"

def print_welcome_message():
    print("Welcome to", COMPANY_NAME.upper())

def print_contact_info():
    print("Contact", COMPANY_NAME, "at info@globaltechsolutions.com") 

# Output: Welcome to GLOBAL TECH SOLUTIONS
print_welcome_message()

# Output: Contact Global Tech Solutions at info@globaltechsolutions.com
print_contact_info()

Welcome to GLOBAL TECH SOLUTIONS
Contact Global Tech Solutions at info@globaltechsolutions.com

In [41]:
def calculate_average(numbers):
    total = 0  # Local variable
    count = len(numbers)  # Local variable
    for num in numbers:
        total += num
    average = total / count
    return average

print(calculate_average([2, 5, 4, 1]))

3.0

## Classes

- Cornerstone of Object oriented programming OOP
-  They provide a structured blueprint for creating objects, the fundamental building blocks of your applications. Son moldes
-  you can define the properties (attributes) and behaviors (methods) that these objects will possess.
- Blue prints for creating objects
- define, caracticas así como funciones, cosas que puede hacer.
- Encapsulation, Inheritance donde puedes tener una clase general y darle sus atributos a una que será mas especializada en base a esta general, Polymophism
- Contractor es el inicializador 
- Reusability Once you've defined a class, you can create multiple instances (objects) of that class.
- Custom classes

In [4]:
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f'Woof! My name is {self.name} and I\'m a {self.breed}.')

In [5]:
dog = Dog('my_dog', 'Golden Retriever')

In [6]:
dog.bark()

Woof! My name is my_dog and I'm a Golden Retriever.

In [9]:
# Functional code block Temperature conversion tool
def celsius_to_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

def fahrenheit_to_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5/9
    return celsius

def convert_temperature(temperature, unit):
    if unit == 'C':
        return celsius_to_fahrenheit(temperature)
    elif unit == 'F':
        return fahrenheit_to_celsius(temperature)
    else:
        return None

In [10]:
temperature_c = 25
temperature_f = 77

converted_f = convert_temperature(temperature_c, 'C')
converted_c = convert_temperature(temperature_f, 'F')

print(f"{temperature_c}°C is equal to {converted_f}°F")
print(f"{temperature_f}°F is equal to {converted_c}°C")

25°C is equal to 77.0°F
77°F is equal to 25.0°C

In [ ]:
#Setting default values: The art of anticipation and elegance
#they make your code easier to use by handling common situations automatically
# mutable default values can change over time, To avoid this pitfall, it's a recommended practice to use None as the default value for mutable arguments.
def calculate_area(width=1, height=1):
    area = width * height
    return area

In [12]:
result = calculate_area() 
print(result)  # Output: 1

1

In [13]:
result = calculate_area(5, 3)  
print(result)  # Output: 15

15

In [14]:
'''Python allows you to define functions that accept a variable number of arguments. 
You can use *args to collect positional arguments into a tuple and **kwargs to collect 
keyword arguments into a dictionary.'''

def flexible_function(*args, **kwargs):
    print("Positional arguments:", args)
    print("Keyword arguments:", kwargs)

flexible_function(1, 2, 3, name="Alice", age=30)

Positional arguments: (1, 2, 3)
Keyword arguments: {'name': 'Alice', 'age': 30}

In [15]:
# full example 
def create_user_profile(name, age, occupation="Student", interests=None): # Use None as default
    """
    Creates a user profile with optional interests.

    Args:
        name (str): The user's name (required).
        age (int): The user's age (required).
        occupation (str, optional): The user's occupation (defaults to "Student").
        interests (list, optional): A list of the user's interests (defaults to None).
    """
    if interests is None:  # Initialize if None
        interests = [] 

    profile = {
        "name": name,
        "age": age,
        "occupation": occupation,
        "interests": interests
    }

    return profile

# Usage
user1 = create_user_profile("Alice", 25, "Software Engineer", ["Coding", "Hiking"])
user2 = create_user_profile("Bob", 18)  # Uses default occupation and no interests
user3 = create_user_profile("Carol", 30, interests=["Gardening", "Reading"])

print(user1)
print(user2)
print(user3)

{'name': 'Alice', 'age': 25, 'occupation': 'Software Engineer', 'interests': ['Coding', 'Hiking']}
{'name': 'Bob', 'age': 18, 'occupation': 'Student', 'interests': []}
{'name': 'Carol', 'age': 30, 'occupation': 'Student', 'interests': ['Gardening', 'Reading']}

In [38]:
#exercise make_sandwich
'''
This function should accept the following parameters:

bread_type (a string representing the type of bread)

filling (a string for the main sandwich filling)

cheese (an optional string for the cheese type, defaulting to "none")

toasted (an optional boolean indicating if the sandwich is toasted, defaulting to False)

Inside the function, construct a descriptive sentence about the sandwich being made, incorporating all the provided details.

Have the function return the sentences shown in the Expected Output section below.
'''
def make_sandwich(
    bread_type: str,
    filling: str,
    cheese: str = "none",
    toasted: bool = False,
) -> str:
    """Return a sentence describing a sandwich order."""
    sentence = "Making a"
    if toasted:
        sentence += " toasted"
    sentence += f" {bread_type} sandwich with {filling}"
    if cheese != "none":
        sentence += f" and {cheese} cheese"
    sentence += "."
    return sentence

In [40]:
#make_sandwich("wheat", "turkey", "cheddar", True)
make_sandwich("rye", "ham")

'Making a rye sandwich with ham.'

In [ ]:
# # pre built modules 
# import math #used for math functions
# import random #used for random number generation
# import datetime #used for date and time operations
# import os #used for operating system functions  
# import re #used for regular expression operations
# import pandas #used for data manipulation and analysis
# import numpy #used for numerical operations
# import scipy #used for scientific computing
# import sklearn #used for machine learning
# import tensorflow #used for deep learning
# import torch #used for machine learning
# import keras #used for deep learning
# import csv #used for working with csv files
# import json #used for working with json files

# library vs module

A Python module, at its core, is simply a file with a .py extension. Think of it as a container that houses a collection of related code components. These components can include:

Functions: Reusable blocks of code that perform specific tasks

Classes: Blueprints for creating objects, which are instances of those classes

Variables: Named containers that store data values

These components work together to provide the module's overall functionality. Let's take a closer look at a Python module in action:

In [ ]:
# File: geometry_calculations.py

import math

def calculate_area_circle(radius):
    """Calculates the area of a circle given its radius."""
    return math.pi * radius**2

def calculate_circumference_circle(radius):
    """Calculates the circumference of a circle given its radius."""
    return 2 * math.pi * radius

class Rectangle:
    """Represents a rectangle with width and height."""

    def __init__(self, width, height):
        self.width = width
        self.height = height

    def calculate_area(self):
        """Calculates the area of the rectangle."""
        return self.width * self.height

    def calculate_perimeter(self):
        """Calculates the perimeter of the rectangle."""
        return 2 * (self.width + self.height)
    
#having this py in the same folder as the notebook we con do for example
# File: main.py

import geometry_calculations

radius = 5
area = geometry_calculations.calculate_area_circle(radius)
circumference = geometry_calculations.calculate_circumference_circle(radius)

print(f"Area of circle: {area}")
print(f"Circumference of circle: {circumference}")

rect = geometry_calculations.Rectangle(4, 6)
rect_area = rect.calculate_area()
rect_perimeter = rect.calculate_perimeter()

print(f"Area of rectangle: {rect_area}")
print(f"Perimeter of rectangle: {rect_perimeter}")

#Other alternative is to make from geometry_calculations import calculate_area_circle, Rectangle

In [42]:
import math 

print(math.sqrt(25))

5.0

- Web development
    - Flask
    - Django
    - Requests
- DS
    - Numpy
    - Pandas
    - Matplotlib
- ML
    - Scikit-learn
    - Pytorch
    - Keras
    - Microsoft Cognitive Toolkit

For installing in terminal use 
pip install library_name

pip connects to the Python Package Index (PyPI), the official repository for Python packages

pip install -r requirements.txt #A requirements file (requirements.txt) is a simple text file that lists all the packages your project depends on, along with their specific versions. This allows anyone to recreate the project environment with a single command.

pip list: Quickly view all installed packages and their versions.

pip show <package>: Get detailed information about a specific package, including its dependencies and location.

pip freeze: Generate a list of your installed packages suitable for a requirements.txt file, perfect for sharing your project's dependencies.

pip check: Verify your environment for any dependency conflicts, helping prevent unexpected errors


Conda, for manage enviroments
Important Conda commands

conda create: Creates a new Conda environment.

conda activate: Activates a specific Conda environment.

conda deactivate: Deactivates the currently active environment.

conda install: Installs packages into the active environment.

conda list: Lists all packages installed in the active environment.

conda search: Searches for available packages in the Conda repositories.

conda search <keyword>: Searches the Conda repositories for packages related to the given keyword.

conda update: Updates a package to its latest version.

conda remove: Uninstalls a package from the active environment.

conda env list: Lists all Conda environments on your system.

Managing packages with Conda

conda install <package-name>: Installs the specified package into your active Conda environment.

conda list <package-name>: Displays information about the specified package, including its version.

conda update <package-name>: Upgrades the specified package to its latest available version.

conda install <package-name>=<version>: Installs a specific version of the specified package.

conda remove <package-name>: Uninstalls the specified package from your active environme

## Data Structures 
- List --> mutable []
- Tuple --> non mutable ()
- Sets, es una colección no ordenada, solo valores únicos {}, aplican operaciones booleanas como union(), intersection(), difference()
- Dicctionary {key: value}
-

In [43]:
#list on mining example

mining_data = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
]

print(mining_data[0][1])

2

In [45]:
#slicing a list

mining_data = [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
]

print(mining_data[0][1:4])

[2, 3, 4]

In [44]:
#dictionary on mining example

mining_data = {
    "X": [1, 2, 3, 4, 5],
    "Y": [6, 7, 8, 9, 10],
    "Z": [11, 12, 13, 14, 15]
}

print(mining_data["X"][1])

2

In [73]:
#this is a nested dictionary
students = {
    "john_smith": {
        "email": "john.smith@example.com",
        "phone": "123-456-7890",
        "address": "123 Main St",
        "grades": [85, 90, 78],
    },
    "maria_garcia": {
        "email": "maria.garcia@example.com",
        "phone": "987-654-3210",
        "address": "456 Oak Avenue",
        "grades": [92, 88, 95]
    },
}

print(students["john_smith"]["email"])

john.smith@example.com

In [46]:
shopping_list = ["apples", "bananas", "milk"]  # List for items
item_quantities = {"apples": 3, "bananas": 1}  # Dictionary for quantities

# User adds an item
shopping_list.append("eggs")
item_quantities["eggs"] = 12 

# User increases the quantity of bananas
item_quantities["bananas"] += 2

# User removes apples
shopping_list.remove("apples")
del item_quantities["apples"]

# Print updated list and dictionary
print(shopping_list)
print(item_quantities)

['bananas', 'milk', 'eggs']
{'bananas': 3, 'eggs': 12}

In [47]:
#exercise 
shopping_cart = []
shopping_cart.append("apple")
shopping_cart.append("banana")
shopping_cart.append("milk")
for item in shopping_cart:
    print(item)

apple
banana
milk

In [74]:
#While dictionaries are incredibly versatile, it's important to be mindful of a few things. 
#Keys must be unique and each key in a dictionary can appear only once. 
# If you try to add a new value with an existing key, the old value will be overwritten.

#example

my_dict = {"a": 1, "b": 2}
my_dict["a"] = 3
print(my_dict)

{'a': 3, 'b': 2}

In [49]:
product_catalog = {
    "SKU123": {
        "name": "Widget A",
        "price": 19.99,
        "quantity": 50},
    "SKU456": {
        "name": "Gadget B",
        "price": 34.95,
        "quantity": 25},
    "SKU789": {
        "name": "Gizmo C",
        "price": 9.99,
        "quantity": 100}
}
# Look up this SKU in your code. 
sku_to_find = "SKU123"
price = product_catalog[sku_to_find]["price"]
print(f"The price of {product_catalog[sku_to_find]['name']} is ${price}")

The price of Widget A is $19.99

## Data Manipulation

- use, Pandas, Numpy, Matplotlib
- data set de ejemplo hay en Scikit learn

In [51]:
import sklearn.datasets as datasets

dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_file',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circles',
 'make_classification',
 'make_friedman1',
 'make_friedman2',
 'make_friedman3',
 'make_gaussian_quantiles',
 'make_hastie_10_2',
 'make_low_rank_matrix',
 'make_moons',
 'make_multilabel_classification',
 'make_regression',
 'make_s_curve',
 'make_sparse_coded_signal',
 'make_sparse_spd_matrix',
 'make_sparse_uncorrelated',
 'make_spd_matrix',
 'make_swiss_roll',
 'textwrap']

In [60]:
from sklearn.datasets import load_iris
import pandas as pd

iris, df_target = load_iris(return_X_y=True, as_frame=True)

df = iris

df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [61]:
df_target.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [58]:
df.target.value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [72]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000

In [54]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [71]:
# Sort DataFrame values by petal length
df.sort_values(by=['petal length (cm)'], ascending=True, inplace=True)
df.head(10)

    sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
22                4.6               3.6                1.0               0.2
13                4.3               3.0                1.1               0.1
14                5.8               4.0                1.2               0.2
35                5.0               3.2                1.2               0.2
16                5.4               3.9                1.3               0.4
41                4.5               2.3                1.3               0.3
42                4.4               3.2                1.3               0.2
40                5.0               3.5                1.3               0.3
36                5.5               3.5                1.3               0.2
2                 4.7               3.2                1.3               0.2

## Searching methods

In [1]:
# bubble sort 
# selection sort 
# Quicksort

def linear_search(data, target):
    """
    Perform a linear search to find the target element inside a list.

    Linear search checks each element one by one, from left to right,
    until it finds the target value or reaches the end of the list.

    Args:
        data (list): The list of elements to search through.
        target: The element we want to find.

    Returns:
        int | str:
            - The index of the target if it is found.
            - -1 if the target is not found.
            - An error message if data is not a list.
    """

    # 1. Validate that the input data is actually a list.
    # This prevents the function from failing if someone passes a string,
    # integer, dictionary, or another incorrect data type.
    if not isinstance(data, list):
        return "Invalid input: data must be a list"

    # 2. Handle the case of an empty list.
    # If the list has no elements, there is nothing to search.
    if not data:
        return -1

    # 3. Loop through the list using indexes.
    # range(len(data)) creates a sequence of indexes:
    # For example, if data has 5 elements, it creates: 0, 1, 2, 3, 4
    for i in range(len(data)):

        # 4. Compare the current element with the target.
        # data[i] means: "the element located at index i".
        if data[i] == target:

            # 5. If the current element matches the target,
            # return the index where the target was found.
            return i

    # 6. If the loop finishes and no match was found,
    # return -1 to indicate that the target is not inside the list.
    return -1

In [4]:
list_example = ["Hello", "World", "Good", "Day", "To", "You"]

target = "Day"
search_1 = linear_search(list_example, target)

print("Result of searching for ", target, " is index ", search_1)

Result of searching for  Day  is index  3

In [5]:
search_2 = linear_search(list_example, "Python")

print("Result of searching for 'Python':", search_2)

Result of searching for 'Python': -1

In [6]:
invalid_data = "Hello World"

search_4 = linear_search(invalid_data, "World")

print("Result with invalid input:", search_4)

Result with invalid input: Invalid input: data must be a list


## Search Algorithms Comparison

| Algorithm | Requirement | Strategy | Speed |
|---|---|---|---|
| Linear Search | The list can be unordered | Checks each element one by one from left to right | Slower for large lists |
| Binary Search | The list must be sorted | Cuts the search space in half at each step | Much faster for large sorted lists |

## Main Search Algorithms

| Search Type | Main Idea | When It Is Useful |
|---|---|---|
| Linear Search | Checks each element one by one | Small datasets or unordered data |
| Binary Search | Repeatedly cuts the search space in half | Large datasets that are already sorted |
| Hash-Based Lookup | Uses a dictionary or set to check if a value exists | Very fast exact searches, such as checking IDs |
| Tree Search | Searches through hierarchical or indexed structures | Databases, indexes, file systems, and decision trees |
| Graph Search | Explores connected nodes | Routes, networks, dependencies, and recommendation systems |

In [11]:
def binary_search(data, target):
    """
    Perform binary search to find the target element inside a sorted list.

    Binary search only works correctly when the input list is sorted.
    It repeatedly checks the middle element and eliminates half of the
    remaining search space.

    Args:
        data (list): A sorted list of elements.
        target: The element we want to find.

    Returns:
        int | str:
            - The index of the target if it is found.
            - -1 if the target is not found.
            - An error message if data is not a list.
    """

    # 1. Validate that data is a list.
    # This prevents errors if someone passes a string, number, dictionary, etc.
    if not isinstance(data, list):
        return "Invalid input: data must be a list"

    # 2. Define the search boundaries.
    # left represents the first index of the current search area.
    # right represents the last index of the current search area.
    left = 0
    right = len(data) - 1

    # 3. Continue searching while there is still a valid search area.
    # If left becomes greater than right, the target is not in the list.
    while left <= right:

        # 4. Find the middle index.
        # This avoids checking every element one by one.
        middle = (left + right) // 2 # floor division

        # 5. Get the value located at the middle index.
        middle_value = data[middle]

        # 6. If the middle value is the target, we found it.
        if middle_value == target:
            return middle

        # 7. If the target is greater than the middle value,
        # it must be on the right side of the list.
        elif target > middle_value:
            left = middle + 1

        # 8. If the target is smaller than the middle value,
        # it must be on the left side of the list.
        else:
            right = middle - 1

    # 9. If the loop finishes, the target was not found.
    return -1

In [13]:
numbers = [3, 7, 12, 18, 25, 31, 44, 58, 72]

result = binary_search(numbers, 31)

print("Result of searching for 31 is index :", result)

Result of searching for 31 is index : 5

In [15]:
def quicksort(cards):
  if len(cards) < 2:
    return cards  # Base case: Already sorted if 0 or 1 element
  else:
    pivot = cards[0]  # Choose first card as pivot
    less = [i for i in cards[1:] if i <= pivot]
    greater = [i for i in cards[1:] if i > pivot]
    return quicksort(less) + [pivot] + quicksort(greater)

In [16]:
# using quicksort

numbers = [3, 7, 12, 18, 25, 31, 44, 58, 72]

sorted_numbers = quicksort(numbers)

print(sorted_numbers)

[3, 7, 12, 18, 25, 31, 44, 58, 72]

"Big O notation." Big O is a way to measure and express how an algorithm's performance changes as the amount of data it's dealing with increases. It's like saying, "If I double the size of my deck of cards, this sorting algorithm will take four times as long." Understanding Big O notation helps you predict how well an algorithm will perform in different situations

In [17]:
import timeit

# List lookup
list_data = list(range(100000))
lookup_value = 99999
list_time = timeit.timeit(lambda: lookup_value in list_data, number=1000)

# Dictionary lookup
dict_data = {i: i for i in range(100000)}
dict_time = timeit.timeit(lambda: lookup_value in dict_data, number=1000)

print("List lookup time:", list_time)
print("Dictionary lookup time:", dict_time)

List lookup time: 0.31771495900466107
Dictionary lookup time: 2.0874998881481588e-05

In [ ]:
# correct data structure explains your code by itself 
# factos: Type of data, Operations, Performance requirements, Memory constraints, Readability and mantainability

## Error handling and Debugging

In [ ]:
#exception handling example 
# classic to use it when reading files
# network connections 
try:
    x = int(input("Enter a number: "))
    result = 10 / x
    print("Result:", result)
except ValueError:
    print("Invalid input. Please enter a valid number.")
except ZeroDivisionError:
    print("Cannot divide by zero. Please enter a non-zero value.")

In [1]:
#try-except-else-finally, example mining engineering with trucks 

file_name = "sample.txt"
try:
    with open(file_name, 'r') as file:
        contents = file.read()
        print(contents)
except FileNotFoundError:
    print("Error: File not found -", file_name)

Error: File not found - sample.txt

In [ ]:
# Logging debugging --> for large complex, insted of print(), use logging
import logging

logging.basicConfig(filename='app.log', level=logging.DEBUG)
logging.debug('This is a debug message')
logging.info('This is an informational   message')
logging.warning('This is a warning message')
logging.error('This is an error message')

In [ ]:
# assertion example
# como una red de seguridad

assert 2 + 2 == 4, "2 + 2 should equal 4"

Debuggers are like time machines for your code. They are best for more complex code. They allow you to pause execution, inspect the current state of variables, and step through your code line by line, observing how values change. 

Most code editors offer integrated debuggers. You set breakpoints in your code, and when the execution reaches a breakpoint, the debugger halts. You can then examine variables, step over or into functions, and even modify variable values on the fly to test different scenarios.

Debuggers provide unparalleled visibility into your code's runtime behavior. They are indispensable for:

Pinpointing the exact line of code where an error occurs.

Understanding complex logic by tracing the flow of data through intricate algorithms.

Testing potential solutions in a controlled environment.

In [ ]:
#Safe file reading function JCA

def read_file_contents(file_path):
    try:
        with open(file_path, "r") as file:
            contents = file.read()
            print(contents)
    except FileNotFoundError:
        print(f"Error: File not found - {file_path}")

In [ ]:
#Read CSV or Excel files as a pandas DataFrame

def read_file_as_dataframe(file_path):
    try:
        if file_path.endswith(".csv"):
            return pd.read_csv(file_path)
        elif file_path.endswith((".xlsx", ".xls")):
            return pd.read_excel(file_path)
        else:
            print("Error: file type not supported")
            return None
    except FileNotFoundError:
        print(f"Error: File not found - {file_path}")
        return None

In [ ]:
def calculate_discount(price, percentage):
    if percentage < 0 or percentage > 100:
        raise ValueError("Discount percentage must be between 0 and 100")
    discount_amount = price * (percentage / 100)
    return price - discount_amount
try:
    print(calculate_discount(100, 150))
except ValueError as e:
    print(f"Error: {e}")

## English to learn

- tangled ball of yarn
- Howdy
- Hover over the 'LEARN' folder
- backbone
- pesky data entry errors
- 
- 
-